# Generated by Django 4.1.2 on 2022-10-11 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_link', models.CharField(max_length=5)),
                ('board_title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.CharField(default='Anon', max_length=35)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='post/images/', verbose_name='Image')),
                ('thumbnail', models.ImageField(blank=True, upload_to='post/thumbnails/')),
                ('video', models.FileField(blank=True, upload_to='post/videos/')),
                ('video_thumb', models.ImageField(blank=True, upload_to='post/videos/thumbs')),
                ('bump', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mboard.board')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mboard.post')),
            ],
        ),
    ]
