# Generated by Django 4.1.2 on 2022-10-11 08:52

from django.db import migrations

boards = {'b': 'Random', 'test': 'test', 'int': 'International'}

bbcodetags = {  # key should be == value[0]; 's'=='s', 'i'=='i'...
    'spoiler': [
        '[spoiler]{TEXT}[/spoiler]', '<span class="spoiler">{TEXT}</span>'
    ],
    's': [
        '[s]{TEXT}[/s]', '<s>{TEXT}</s>'
    ],
    'i': [
        '[i]{TEXT}[/i]', '<em>{TEXT}</em>'
    ],
    'b': [
        '[b]{TEXT}[/b]', '<strong>{TEXT}</strong>'
    ]
}


def prepopulate_db(apps, schema_editor):
    Board = apps.get_model('mboard', 'Board')
    for k, v in boards.items():
        Board.objects.create(board_link=k, board_title=v)

    BBCodeTag = apps.get_model('precise_bbcode', 'BBCodeTag')
    for k, v in bbcodetags.items():
        BBCodeTag.objects.create(tag_name=k, tag_definition=v[0], html_replacement=v[1])


class Migration(migrations.Migration):
    dependencies = [
        ('mboard', '0001_initial'),
        ('precise_bbcode', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(prepopulate_db)
    ]
