# Generated by Django 4.1.2 on 2022-11-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mboard', '0002_auto_20221011_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cookie',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
