# Generated by Django 4.1.2 on 2022-10-26 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('mboard', '0003_remove_post_poster_post_session_rating_calctime_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rating',
            name='unique_constraint',
        ),
        migrations.AddField(
            model_name='calctime',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mboard.board', to_field='board_link'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mboard.board', to_field='board_link'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='board',
            name='board_link',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='calctime',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions.session'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('board', 'user', 'target'), name='unique_constraint'),
        ),
    ]
