# Generated by Django 4.1.2 on 2022-11-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mboard', '0003_post_cookie'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
