# Generated by Django 4.1.2 on 2022-10-17 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('mboard', '0003_post_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.session'),
        ),
    ]
