# Generated by Django 4.1.2 on 2022-10-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mboard', '0004_remove_rating_unique_constraint_calctime_board_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='vote_time',
            field=models.DateTimeField(null=True),
        ),
    ]
